nohup: ignoring input
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00014.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00024.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00031.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00134.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00147.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00150.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00169.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00170.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00171.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00172.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00174.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00175.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00176.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00177.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00239.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00240.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00241.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00242.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00244.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00245.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00246.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00247.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00286.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00300.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00340.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00410.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00411.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00412.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00413.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00480.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00511.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00514.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00524.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00525.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00526.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00527.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00560.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00630.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00677.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00748.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00768.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00798.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00800.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00844.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00845.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00850.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00860.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00873.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00886.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00891.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00906.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00910.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00912.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00918.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00927.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00929.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00931.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00940.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K00943.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01006.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01007.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01046.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01054.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01056.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01494.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01520.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01595.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01623.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01624.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01626.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01661.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01676.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01677.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01678.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01679.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01681.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01682.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01689.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01735.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01736.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01803.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01810.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01834.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01851.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01902.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01903.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01911.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01958.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01959.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K01960.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02006.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02007.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02008.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02009.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02036.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02037.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02038.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02040.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02045.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02046.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02047.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02048.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02225.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02226.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02227.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02231.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02232.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02233.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02291.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02293.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02361.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02517.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02527.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02535.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02536.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02548.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02549.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02551.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02552.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02560.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02703.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02704.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02705.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02706.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02707.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02708.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02863.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02864.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02867.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02871.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02874.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02876.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02878.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02879.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02881.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02884.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02886.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02887.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02888.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02890.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02892.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02895.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02897.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02899.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02902.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02904.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02906.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02907.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02909.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02911.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02913.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02914.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02916.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02919.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02926.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02931.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02933.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02935.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02939.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02945.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02946.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02948.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02950.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02952.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02954.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02956.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02959.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02961.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02963.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02965.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02967.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02968.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02970.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02982.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02986.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02988.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02990.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02992.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02994.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K02996.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K03040.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K03043.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K03046.fa.db
perl /netapp/home/sharpton/projects/mouse_microbiome/scripts/job_launcher.pl --opt2 /netapp/home/sharpton/projects/mouse_microbiome/lastdb/prelim/K03048.fa.db
